tensorflow-jupyter:
  ports:
  - 8888:8888/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  entrypoint:
  - /bin/sh
  - -c
  - jupyter notebook --port=8888 --ip=0.0.0.0
  image: davidchiu/tensorflow09:latest
  hostname: tf_jupyter
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - tensorflow:/root/notebook
  privileged: true
  working_dir: /root/notebook
  stdin_open: true
  net: host
  volume_driver: convoy-gluster
worker:
  ports:
  - 32222:22/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  hostname: tf_worker
  image: davidchiu/tensorflow09:latest
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - tensorflow:/root/notebook
  working_dir: /root/notebook
  stdin_open: true
  net: host
  volume_driver: convoy-gluster
ps:
  ports:
  - 33222:22/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: tf_ps
  image: davidchiu/tensorflow09:latest
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - tensorflow:/root/notebook
  working_dir: /root/notebook
  stdin_open: true
  net: host
  volume_driver: convoy-gluster
