.catalog:
  name: TensorFlow
  version: v0.9
  description: |
    TensorFlow
  uuid: tensorflow-0
  questions:
    - variable: "PUBLIC_PORT"
      label: "Port number"
      type: "int"
      default: 8888
      required: false
      description: Service that is running GlusterFS
    - variable: "CONVOY_SERVICE"
      label: "Convoy Gluster Service"
      type: "string"
      default: "convoy-gluster"
      required: true
      description: Service that is running GlusterFS
    - variable: "CONVOY_VOL"
      description: "Convoy gluster volume name"
      label: "Volume name:"
      required: true
      default: tf_vol
      type: "string"
    - variable: "MOUNT_PATH"
      description: "Convoy gluster mount path"
      label: "Mount path:"
      required: true
      default: /notebooks
      type: "string"
tensorflow:
  scale: 1