tf-jupyter:
  ports:
  - ${PUBLIC_PORT}:8888/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  entrypoint:
  - /bin/sh
  - -c
  - jupyter notebook --port=8888 --ip=0.0.0.0
  image: davidchiu/tensorflow09:gpu-jupyter
  hostname: tf_jupyter
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - ${CONVOY_VOL}:${MOUNT_PATH}
  working_dir: ${MOUNT_PATH}
  stdin_open: true
  volume_driver: ${CONVOY_SERVICE}
tf-worker:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  hostname: tf_worker
  image: davidchiu/tensorflow09:gpu-ssh
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - ${CONVOY_VOL}:${MOUNT_PATH}
  working_dir: ${MOUNT_PATH}
  stdin_open: true
  volume_driver: ${CONVOY_SERVICE}
tf-ps:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: tf_ps
  image: davidchiu/tensorflow09:gpu-ssh
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  - ${CONVOY_VOL}:${MOUNT_PATH}
  working_dir: ${MOUNT_PATH}
  stdin_open: true
  volume_driver: ${CONVOY_SERVICE}
