.catalog:
  name: TensorFlow-GPU-DIST
  version: v0.9
  description: |
    TensorFlow-GPU Distributed
  uuid: tensorflow-gpu-dist-0
  questions:
    - variable: "WORKER_NUM"
      label: "worker number"
      type: "int"
      default: 6
      required: true
      description: worker number setting
    - variable: "PUBLIC_PORT"
      label: "Port number"
      type: "int"
      default: 8888
      required: false
      description: jupyter-notebooks public port
    - variable: "CONVOY_SERVICE"
      label: "Convoy NFS Service"
      type: "string"
      default: "convoy-nfs"
      required: true
      description: Service that is running convoy-nfs
    - variable: "CONVOY_VOL"
      description: "Convoy nfs volume name"
      label: "Volume name:"
      required: true
      default: tensorflow_volume_gpu
      type: "string"
    - variable: "MOUNT_PATH"
      description: "Convoy gluster mount path"
      label: "Mount path:"
      required: true
      default: /notebooks
      type: "string"
tf-jupyter:
  scale: 1
tf-worker:
  scale: ${WORKER_NUM}
tf-ps:
  scale: 1
